const currencyCodes = `INR AED AFN ALL AMD ANG AOA ARS AUD AWG AZN BAM BBD BDT BGN BHD BIF BMD BND BOB BRL BSD BTN BWP BYN BZD CAD CDF CHF CLF CLP CNH CNY COP CRC CUP CVE CZK DJF DKK DOP DZD EGP ERN ETB EUR FJD FKP FOK GBP GEL GGP GHS GIP GMD GNF GTQ GYD HKD HNL HRK HTG HUF IDR ILS IMP IQD IRR ISK JEP JMD JOD JPY KES KGS KHR KID KMF KRW KWD KYD KZT LAK LBP LKR LRD LSL LYD MAD MDL MGA MKD MMK MNT MOP MRU MUR MVR MWK MXN MYR MZN NAD NGN NIO NOK NPR NZD OMR PAB PEN PGK PHP PKR PLN PYG QAR RON RSD RUB RWF SAR SBD SCR SDG SEK SGD SHP SLE SLL SOS SRD SSP STN SYP SZL THB TJS TMT TND TOP TRY TTD TVD TWD TZS UAH UGX USD UYU UZS VES VND VUV WST XAF XCD XCG XDR XOF XPF YER ZAR ZMW ZWG ZWL`.split(' ');

const names={USD:'US Dollar',EUR:'Euro',GBP:'British Pound',INR:'Indian Rupee',JPY:'Japanese Yen',AUD:'Australian Dollar',CAD:'Canadian Dollar',CHF:'Swiss Franc',CNY:'Chinese Yuan',AED:'UAE Dirham',SGD:'Singapore Dollar',NZD:'New Zealand Dollar',SAR:'Saudi Riyal',ZAR:'South African Rand',BRL:'Brazilian Real',MXN:'Mexican Peso',KRW:'South Korean Won',SEK:'Swedish Krona',NOK:'Norwegian Krone',DKK:'Danish Krone',PLN:'Polish Zloty',TRY:'Turkish Lira',THB:'Thai Baht',HKD:'Hong Kong Dollar',PKR:'Pakistani Rupee',LKR:'Sri Lankan Rupee',NPR:'Nepalese Rupee'};
const $=id=>document.getElementById(id);const from=$('from'),to=$('to'),apiUrl=$('apiUrl'),status=$('status'),result=$('result');
const saved=localStorage.getItem('currencyApiBase')||'';apiUrl.value=saved;
currencyCodes.forEach(code=>{const label=`${code} — ${names[code]||code}`;from.add(new Option(label,code));to.add(new Option(label,code))});from.value='USD';to.value='INR';
function setStatus(text,type='idle'){status.textContent=text;status.className=`status ${type}`}
function base(){return apiUrl.value.trim().replace(/\/$/,'')}
function endpointFor(code){return `${base()}/api/currencies/${encodeURIComponent(code)}`}
function showMessage(title,detail,icon='!'){result.className='result';result.innerHTML=`<span class="result-icon">${icon}</span><div><strong>${escapeHtml(title)}</strong><small>${escapeHtml(detail)}</small></div>`}
$('saveApi').onclick=()=>{const value=base();if(!value){localStorage.removeItem('currencyApiBase');setStatus('Endpoint required','error');showMessage('Configure your MuleSoft API','Enter a public base URL, for example https://your-api.example.com. Do not include /api/currencies/...','!');return}try{new URL(value);localStorage.setItem('currencyApiBase',value);setStatus('Endpoint saved','ok');showMessage('Endpoint configured',`${value} is ready. You can now convert currencies.`,'✓')}catch{setStatus('Invalid endpoint','error');showMessage('Invalid endpoint','Enter a complete URL beginning with http:// or https://','!')}};
$('clearApi').onclick=()=>{apiUrl.value='';localStorage.removeItem('currencyApiBase');setStatus('Endpoint cleared','idle');showMessage('Endpoint cleared','Configure the API endpoint before using live conversion.','↗')};
$('testApi').onclick=async()=>{const root=base();if(!root){setStatus('API endpoint required','error');showMessage('Configure endpoint first','A public MuleSoft API base URL is required before testing.','!');return}try{new URL(root)}catch{setStatus('Invalid endpoint','error');showMessage('Invalid endpoint','Use a complete URL such as https://api.example.com','!');return}setStatus('Testing…');showMessage('Testing Currency API','Calling the USD currency endpoint…','…');try{const response=await fetch(endpointFor('USD'),{headers:{Accept:'application/json'}});const text=await response.text();if(!response.ok)throw new Error(`HTTP ${response.status}${text?` — ${text.slice(0,120)}`:''}`);let data;try{data=JSON.parse(text)}catch{throw new Error('API returned non-JSON content')}if(!data||typeof data!=='object')throw new Error('API returned an unexpected response');setStatus('API connected','ok');showMessage('API connection successful','The endpoint returned valid JSON for USD. Conversion is ready.','✓')}catch(error){setStatus('Connection failed','error');showMessage('Could not reach the API',`${error.message}. Check the MuleSoft URL, deployment status, HTTPS and CORS configuration.`,'!')}};
$('swap').onclick=()=>{[from.value,to.value]=[to.value,from.value]};
$('convert').onclick=async()=>{const amount=Number($('amount').value);const source=from.value,target=to.value;const root=base();if(!amount||amount<=0){setStatus('Enter an amount','error');showMessage('Invalid amount','Enter an amount greater than 0.','!');return}if(!root){setStatus('API endpoint required','error');showMessage('Configure your MuleSoft API first','Open API endpoint settings, enter the public backend URL, save it, then try again.','!');$('apiUrl').focus();return}try{new URL(root)}catch{setStatus('Invalid endpoint','error');showMessage('Invalid API endpoint','Enter a complete URL beginning with http:// or https://.','!');$('apiUrl').focus();return}if(source===target){showResult(amount,source,target,1,{conversion_rate:1});setStatus('Converted','ok');return}setStatus('Fetching rate…');showMessage('Calling Currency API',`Fetching the latest ${source} rates…`,'…');try{const response=await fetch(endpointFor(source),{headers:{Accept:'application/json'}});const text=await response.text();if(!response.ok)throw new Error(`API returned HTTP ${response.status}`);let data;try{data=JSON.parse(text)}catch{throw new Error('API returned invalid JSON')}const rate=findRate(data,target);if(rate==null)throw new Error(`No ${target} rate found in the API response`);showResult(amount,source,target,rate,data);setStatus('Live response','ok')}catch(error){setStatus('Request failed','error');showMessage('Could not complete conversion',`${error.message}. Verify the endpoint, MuleSoft deployment and browser CORS configuration.`,'!')}};
function findRate(data,target){const candidates=[data.rates?.[target],data.conversion_rates?.[target],data.exchange_rates?.[target],data[target],data.quotes?.[target],data.quotes?.[`${data.base_code||data.base||''}${target}`]];for(const x of candidates){if(typeof x==='number')return x;if(typeof x==='string'&&!Number.isNaN(Number(x)))return Number(x)}return null}
function showResult(amount,source,target,rate,data){const value=amount*rate;result.className='result success';result.innerHTML=`<span class="result-icon">✓</span><div><strong>${format(amount)} ${source} = ${format(value)} ${target}</strong><small>1 ${source} = ${format(rate)} ${target}${data.time_last_update_utc?` • Updated ${escapeHtml(data.time_last_update_utc)}`:''}</small></div>`}
function format(n){return new Intl.NumberFormat(undefined,{maximumFractionDigits:6}).format(n)}function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('amount').addEventListener('keydown',e=>{if(e.key==='Enter')$('convert').click()});
apiUrl.addEventListener('keydown',e=>{if(e.key==='Enter')$('saveApi').click()});