const currencies=[['USD','US Dollar'],['EUR','Euro'],['GBP','British Pound'],['INR','Indian Rupee'],['JPY','Japanese Yen'],['AUD','Australian Dollar'],['CAD','Canadian Dollar'],['CHF','Swiss Franc'],['CNY','Chinese Yuan'],['AED','UAE Dirham'],['SGD','Singapore Dollar'],['NZD','New Zealand Dollar'],['SAR','Saudi Riyal'],['ZAR','South African Rand'],['BRL','Brazilian Real'],['MXN','Mexican Peso'],['KRW','South Korean Won'],['SEK','Swedish Krona'],['NOK','Norwegian Krone'],['DKK','Danish Krone']];
const $=id=>document.getElementById(id);const from=$('from'),to=$('to'),apiUrl=$('apiUrl'),status=$('status'),result=$('result');
const saved=localStorage.getItem('currencyApiBase')||'';apiUrl.value=saved;
currencies.forEach(([code,name])=>{from.add(new Option(`${code} — ${name}`,code));to.add(new Option(`${code} — ${name}`,code))});from.value='USD';to.value='INR';
function setStatus(text,type='idle'){status.textContent=text;status.className=`status ${type}`}
function base(){return apiUrl.value.trim().replace(/\/$/,'')}
$('saveApi').onclick=()=>{const value=base();localStorage.setItem('currencyApiBase',value);setStatus(value?'Endpoint saved':'Enter an endpoint','ok')};
$('swap').onclick=()=>{[from.value,to.value]=[to.value,from.value]};
$('convert').onclick=async()=>{const amount=Number($('amount').value);const source=from.value,target=to.value;const root=base();if(!amount||amount<=0){setStatus('Enter an amount','error');return}if(!root){setStatus('API endpoint required','error');result.className='result';result.innerHTML='<span class="result-icon">!</span><div><strong>Configure your MuleSoft API first</strong><small>Open API endpoint settings and enter the public backend URL.</small></div>';return}if(source===target){showResult(amount,source,target,1,{conversion_rate:1});return}setStatus('Fetching rate…');result.className='result';result.innerHTML='<span class="result-icon">…</span><div><strong>Calling Currency API</strong><small>Fetching the latest rate for '+source+'…</small></div>';try{const response=await fetch(`${root}/api/currencies/${encodeURIComponent(source)}`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`API returned ${response.status}`);const data=await response.json();const rate=findRate(data,target);if(rate==null)throw new Error(`No ${target} rate found in response`);showResult(amount,source,target,rate,data);setStatus('Live response','ok')}catch(error){setStatus('Request failed','error');result.innerHTML='<span class="result-icon">!</span><div><strong>Could not reach the API</strong><small>'+escapeHtml(error.message)+'. Check the endpoint and CORS configuration.</small></div>'}};
function findRate(data,target){const candidates=[data.rates?.[target],data.conversion_rates?.[target],data.exchange_rates?.[target],data[target],data.quotes?.[target],data.quotes?.[`${data.base_code||data.base||''}${target}`]];for(const x of candidates){if(typeof x==='number')return x;if(typeof x==='string'&&!Number.isNaN(Number(x)))return Number(x)}return null}
function showResult(amount,source,target,rate,data){const value=amount*rate;result.innerHTML=`<span class="result-icon">↗</span><div><strong>${format(amount)} ${source} = ${format(value)} ${target}</strong><small>1 ${source} = ${format(rate)} ${target}${data.time_last_update_utc?` • Updated ${escapeHtml(data.time_last_update_utc)}`:''}</small></div>`}
function format(n){return new Intl.NumberFormat(undefined,{maximumFractionDigits:6}).format(n)}function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('amount').addEventListener('keydown',e=>{if(e.key==='Enter')$('convert').click()});
