name: Deploy Mule API

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to CloudHub 2.0?'
        required: true
        default: 'no'
        type: choice
        options:
          - 'no'
          - 'yes'

jobs:

  build:
    name: Build Mule Application
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build Mule application
        run: |
          mvn -B clean package \
            -DskipTests \
            -Dapp.name=currency-api \
            -Denvironment=Sandbox

      - name: Upload Mule application
        uses: actions/upload-artifact@v4
        with:
          name: currency-api-jar
          path: target/*-mule-application.jar


  deploy:
    name: Deploy to CloudHub 2.0
    needs: build

    if: >
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.deploy == 'yes'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Deploy to CloudHub 2.0
        env:
          CONNECTED_APP_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
          CONNECTED_APP_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}

        run: |
          mvn -B clean deploy \
            -DmuleDeploy \
            -DskipTests \
            -Dapp.name=currency-api \
            -Denvironment=Sandbox \
            -DconnectedApp.clientId="${CONNECTED_APP_CLIENT_ID}" \
            -DconnectedApp.clientSecret="${CONNECTED_APP_CLIENT_SECRET}"
