name: MuleSoft CI/CD Pipeline

on:
  push:
    branches:
      - main
      - stg

  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy application to CloudHub 2.0?"
        required: true
        type: choice
        options:
          - "yes"
          - "no"
        default: "yes"

jobs:

  build:
    name: Build Mule Application
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build Mule application
        run: |
          mvn -B clean package \
            -DskipTests

      - name: Upload Mule artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-application
          path: target/*.jar


  deploy:
    name: Deploy to CloudHub 2.0
    needs: build

    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' &&
       github.event.inputs.deploy == 'yes')

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Download Mule artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-application
          path: target

      - name: Deploy to CloudHub 2.0
        env:
          CONNECTED_APP_CLIENT_ID: ${{ vars.CONNECTED_APP_CLIENT_ID }}
          CONNECTED_APP_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}

        run: |
          mvn -B deploy \
            -DmuleDeploy \
            -DskipTests \
            -Dapp.name=currency-api \
            -Denvironment=Sandbox \
            -DconnectedApp.clientId="${CONNECTED_APP_CLIENT_ID}" \
            -DconnectedApp.clientSecret="${CONNECTED_APP_CLIENT_SECRET}" \
            -DconnectedApp.grantType=client_credentials
